In [1]:
#Pandas : Panel Data 
## ekonometrik ve finansal çalışmalar için ortaya çıkmış
# İki yeni veri yapısı: Series ve DataFrame yapısını kullanır

NumPy'nin ndarray veri yapısı, tipik olarak sayısal hesaplama görevlerinde görülen temiz, iyi organize edilmiş veri türü için temel özellikler sağlar. Bu amaca çok iyi hizmet etse de, daha fazla esnekliğe ihtiyaç duyduğumuzda (örneğin, verilere etiket eklemek, eksik verilerle çalışmak vb.) Ve öğe bazlı  iyi eşleşmeyen işlemlere teşebbüs ettiğimizde (örneğin, Gruplamalar, pivotlar, vb.) daha esnek fonksiyonlar sunan bir kütüphaneye ihtiyaç duyarız.
Bunların her biri çevremizdeki dünyadaki birçok formda bulunan daha az yapılandırılmış verileri analiz etmenin önemli bir parçasıdır. Pandas ve özellikle onun Series ve DataFrame nesneleri, NumPy array yapısını temel alır ve bir veri bilimcisinin zamanının çoğunu işgal eden bu tür "veri işleme" görevlerine verimli erişim sağlar.

# Pandas Serisi Oluşturmak

In [1]:
import pandas as pd

In [2]:
pd.Series?

In [3]:
import numpy as np 

In [4]:
a=np.array([12,87,63,14])

In [5]:
a

array([12, 87, 63, 14])

In [7]:
a.shape

(4,)

In [8]:
MySeri=pd.Series([12,87,63,14])

In [15]:
MySeri

0    12
1    87
2    63
3    14
dtype: int64

In [9]:
MySeri.shape

(4,)

In [10]:
type(a)

numpy.ndarray

In [12]:
MySeri.dtype

dtype('int64')

In [94]:
MySeri[1] # indeksleme

87

In [96]:
MySeri

0    12
1    87
2    63
3    14
dtype: int64

In [ ]:
# serinin_adı[start:stop:step]

In [14]:
MySeri[0::2] #dilimle (slicing)

0    12
2    63
dtype: int64

In [17]:
MySeri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [10]:
seri.size

4

In [11]:
seri.ndim

1

In [19]:
MySeri.keys


<bound method Series.keys of 0    12
1    87
2    63
3    14
dtype: int64>

In [22]:
MySeri.items()

In [25]:
t=list(MySeri.items())

In [27]:
type(t)

list

In [28]:
MySeri.values


array([12, 87, 63, 14], dtype=int64)

In [26]:
MySeri.values

array([12, 87, 63, 14], dtype=int64)

In [27]:
 # numpy array'e donüştürüyor , Önemli!!!
type(MySeri.values)# numpy array tipi



numpy.ndarray

In [28]:
type(MySeri) # pandas da seri tipi 

pandas.core.series.Series

In [99]:
type(MySeri.values)

numpy.ndarray

In [100]:
Seri_Np=MySeri.values

In [101]:
Seri_Np

array([12, 87, 63, 14], dtype=int64)

In [102]:
MySeri.head(2)

0    12
1    87
dtype: int64

In [103]:
MySeri

0    12
1    87
2    63
3    14
dtype: int64

In [104]:
MySeri.ndim

1

In [29]:
MySeri.tail(5)

0    12
1    87
2    63
3    14
dtype: int64

In [99]:
seri.tail(2)

2    63
3    14
dtype: int64

In [29]:
seri2=pd.Series([98,23,333,5],dtype='float')
seri2

0     98.0
1     23.0
2    333.0
3      5.0
dtype: float64

In [31]:
seri2=pd.Series([98,23,33,5],index=["boy","kilo","d","d"])
seri2

boy     98
kilo    23
d       33
d        5
dtype: int64

In [32]:
seri2['d']

d    33
d     5
dtype: int64

In [110]:
pd.Series?

In [118]:
seri2[0]

98

In [117]:
seri2['a']

98

In [119]:
seri2["a"]


98

In [33]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'Texas2': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [34]:
population_dict

{'California': 38332521,
 'Texas': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [34]:
population_dict['California':'Florida']

TypeError: unhashable type: 'slice'

In [35]:
population['California':'Florida']

California    38332521
Texas         19651127
Florida       19552860
dtype: int64

In [36]:
population['California']

38332521

In [37]:
type(population)

pandas.core.series.Series

In [38]:
type(population_dict)

dict

Bir dict tipinin aksine, Series ayrıca dilimleme gibi dizi tarzı işlemleri de destekler:

In [15]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [128]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [135]:
'Texas' in population

True

In [136]:
"DC" in population

False

In [137]:
population["Texas"]

26448193

In [138]:
population["Texas"]=30000000

In [139]:
population

California    38332521
Texas         30000000
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
sozluk33={"reg":10,"log":15,"cart":23}

In [18]:
seri33=pd.Series(sozluk33)

In [19]:
seri33.index

Index(['reg', 'log', 'cart'], dtype='object')

In [ ]:
# pandas 'dan numpy çevirmek için : values
#Aşağıdaki kodda ise, numpy'dan pandas'a donuşüm yapıyoruz : Series

In [36]:
import numpy as np
a=np.array([111,2,333])# numpy array tipi
seri4=pd.Series(a) # array tipini , pandas series tipine cevirdim !!!!! Önemli

In [38]:
type(seri4)

pandas.core.series.Series

In [37]:
seri4.values # series'i numpy cevirdim

array([111,   2, 333])

In [131]:
type(a)

numpy.ndarray

In [132]:
seri4=pd.Series(a)

In [133]:
seri4


0    111
1      2
2    333
dtype: int32

In [134]:
type(seri4)

pandas.core.series.Series

In [27]:
seriy=pd.Series(sozluk33)

In [28]:
seriy

reg     10
log     15
cart    23
dtype: int64

In [ ]:
"reg" in seriy # reg key değeri seri3'un içinde var mı

In [ ]:
"a" in seriy

In [30]:
seriy["reg"]=20

In [32]:
seriy

reg     20
log     15
cart    23
dtype: int64

# Pandas DataFrame oluşturma

Series ile tek boyutlu indeksli diziler oluştururken, dataframe ile iki boyutlu indeksli diziler oluşturuyoruz

In [40]:
l=[22,33,44,55]
l

[22, 33, 44, 55]

In [41]:
ss=pd.Series(l)

In [42]:
ss.ndim

1

In [43]:
ss.shape

(4,)

In [46]:
ss

0    22
1    33
2    44
3    55
dtype: int64

In [47]:
aa=pd.DataFrame(l)

In [45]:
aa.ndim

2

In [48]:
aa

0
0  22
1  33
2  44
3  55

In [58]:
aa.shape

(4, 1)

In [49]:
import numpy as np
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
df=pd.DataFrame(m,columns=["feature1","feature2","feature3"])

In [52]:
pd.DataFrame?

In [51]:
df

feature1  feature2  feature3
0         1         2         3
1         4         5         6
2         7         8         9

In [44]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [53]:
df.columns=("v1","v2","v3")

In [54]:
df

v1  v2  v3
0   1   2   3
1   4   5   6
2   7   8   9

In [55]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['v1', 'v2', 'v3'], dtype='object')]

In [56]:
df.shape

(3, 3)

In [57]:
df.ndim

2

In [58]:
df.size

9

In [59]:
df.values # pandas artık numpy array nesnesine cevirdi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
type(df.values)

numpy.ndarray

In [62]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]


In [64]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [44]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [65]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [47]:
#İki boyutlu bir NumPy dizisinden

In [66]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['c1', 'c2'],
             index=['a', 'b', 'c'])

c1        c2
a  0.978297  0.532586
b  0.143702  0.833256
c  0.085304  0.840143

# Veri Seçimi : İndeksleme ve dilimleme


In [48]:
#Serilerde

In [67]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [69]:
#Veri ekleme
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [64]:
# slicing by explicit index 
data['a':'e':3]

a    0.25
d    1.00
dtype: float64

In [72]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [70]:
# slicing by implicit integer index : örtülü (örtük) dilimleme
data[0:2] # 0'dan 2. indekse kadar olanını al. yani sıfır dahil 2 dahil değil

a    0.25
b    0.50
dtype: float64

In [71]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [74]:
# fancy indexing
data[['a','d']] # sadece a ve d'yi getir.

a    0.25
d    1.00
dtype: float64

In [76]:
data['b':'e'] # açık indekse gore (explicit)

b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [77]:
data 

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [78]:
data[1:4] #örtülü (implicit)

b    0.50
c    0.75
d    1.00
dtype: float64

# Indexers: loc, iloc

Örneğin, Serinizin açık bir tamsayı indeksi varsa, veriler [1] gibi bir indeksleme işlemi açık indeksleri kullanırken, veri [1: 3] gibi bir dilimleme işlemi örtük Python tarzı indeksi kullanır.

In [79]:
data = pd.Series(['xx', 'yy', 'zz'], index=[1, 3, 5])
data

1    xx
3    yy
5    zz
dtype: object

In [80]:
# data ya ait gizli index değerleri : 0 1 2
# aşikar index değerleri : 1 3 5

In [81]:
# explicit index when indexing :aşikar indeksleme
data[1]

'xx'

In [82]:
# implicit index when slicing :örtülü indekleme (dilimleme yani slicing işleminde)
data[1:3]

3    yy
5    zz
dtype: object

In [83]:
# İşte bu karmaşıklığı gidermek için pandas'da loc ve iloc diye iki özellik var
#loc niteliği, her zaman açık dizine başvuran dizinlemeye ve dilimlemeye izin verir:

In [84]:
data.loc[1] # açık indeksleme

'xx'

In [85]:
data.loc[1:3]

1    xx
3    yy
dtype: object

In [86]:
#İloc niteliği, her zaman örtük Python tarzı dizine başvuran dizin oluşturmaya ve dilimlemeye izin verir:
data.iloc[1]

'yy'

In [87]:
data.iloc[1:3]

3    yy
5    zz
dtype: object

# Dataframe' de veri seçimi

In [92]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 
                 'Illinois': 12882135})
data = pd.DataFrame({'area1':area, 'pop':pop})
data

area1       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [93]:
data['area1']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area1, dtype: int64

In [94]:
data.area1

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area1, dtype: int64

In [96]:
data.pop

<bound method DataFrame.pop of              area1       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [97]:
data["pop"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [173]:
data.area # bu kullanım tavsiye edilmiyor

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [174]:
data.pop # kullanılmamalı çünkü pop diye bir fonksiyonu var

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [175]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [112]:
data['density'] = data['pop'] / data['area1']
data

area1       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [71]:
#np.array cevirmek için

In [177]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [82]:
data

area1      pop1     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [98]:
data.T

California     Texas  New York   Florida  Illinois
area1      423967    695662    141297    170312    149995
pop      38332521  26448193  19651127  19552860  12882135

In [100]:
data

area1       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [104]:
data

area1       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [107]:
data.desc()

AttributeError: 'DataFrame' object has no attribute 'desc'

In [101]:
dt=data.T # transpozunu aldım

In [103]:
dt

California     Texas  New York   Florida  Illinois
area1      423967    695662    141297    170312    149995
pop      38332521  26448193  19651127  19552860  12882135

In [102]:
dt["Texas"]

area1      695662
pop      26448193
Name: Texas, dtype: int64

In [110]:
data

area1       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [180]:
data.iloc[:3, :2] #Örtülü indeksleme (implict) 0. 1.  ve 2. satırların, 0. ve 1. sutundaki değerlerini getir.

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [ ]:
# Açıklama : iloc'da son dahil olmaz, loc'da son verilen indeks değeri dahil olur.

In [108]:
data.loc[:'Texas', :'pop1'] # satır için Baştan başla, Texas dahil al, sutun için baştan başla pop dahil al.

area1       pop
California  423967  38332521
Texas       695662  26448193

In [113]:
data.loc[data.density > 100, ['area1', 'density']]

area1     density
New York  141297  139.076746
Florida   170312  114.806121

In [115]:
data

area1       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [116]:
data.iloc[0, 2] = 90
data
data.iloc[2,1]=8

In [188]:
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297         8  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [81]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [82]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [83]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

## Eleman işlemleri

In [128]:
s1=np.random.randint(10,size=5)
s2=np.random.randint(10,size=5)
s3=np.random.randint(10,size=5)
sozluk_s={"vars1":s1,"vars2":s2,"vars3":s3}

In [129]:
df=pd.DataFrame(sozluk_s)
df

vars1  vars2  vars3
0      8      6      3
1      1      2      6
2      4      0      3
3      8      0      0
4      9      1      9

In [134]:
df[2:4] # index değerine göre slice ediyor

vars1  vars2  vars3
2      4      0      3
3      8      0      0

In [55]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [135]:
df.index=["a","b","c","d","e"]

In [136]:
df

vars1  vars2  vars3
a      8      6      3
b      1      2      6
c      4      0      3
d      8      0      0
e      9      1      9

In [138]:
df.drop("a",axis=0)
df 


vars1  vars2  vars3
a      8      6      3
b      1      2      6
c      4      0      3
d      8      0      0
e      9      1      9

In [59]:
df

var1  var2  var3
a     5     7     5
b     9     1     9
c     9     7     8
d     6     6     7
e     3     7     8

In [139]:
df.drop("a",axis=0,inplace=True)

In [140]:
df

vars1  vars2  vars3
b      1      2      6
c      4      0      3
d      8      0      0
e      9      1      9

In [61]:
df

var1  var2  var3
b     9     1     9
c     9     7     8
d     6     6     7
e     3     7     8

In [192]:
l=["var1","var4","var2"]
l2=["var1","var2"]

In [193]:
for i in l:
    print (i in df)

False
False
False


In [190]:
l

[22, 33, 44, 55]

In [67]:
df.drop(l2,axis=1) # degisken sildim

var3
b     9
c     8
d     7
e     8

In [142]:
df["vars4"]=df["vars1"]/df["vars2"]

In [143]:
df

vars1  vars2  vars3  vars4
b      1      2      6    0.5
c      4      0      3    inf
d      8      0      0    inf
e      9      1      9    9.0

In [145]:
df2=pd.DataFrame(np.random.randint(1,30,size=(10,3)),columns=["var1","var2","var3"])
df2.loc[0:3] # loc fonksiyonu, en son indexi de alıyor

var1  var2  var3
0     9     3    18
1    17     5    10
2    20    26    11
3    23    22     4

In [76]:
df2.iloc[0:3] # 0 dan 3'e kadar , 3 almıyor


0   1   2
0  13  10  18
1  13  26   3
2  27  13  25

In [147]:
df2.iloc[0:3]["var2"]

0     3
1     5
2    26
Name: var2, dtype: int32

In [148]:
df2 # var1 sutunundaki , 15'den buyuk degerleri listele

var1  var2  var3
0     9     3    18
1    17     5    10
2    20    26    11
3    23    22     4
4     7     7    15
5    14    27    14
6     9    24    15
7    11    19     2
8    11     7    18
9    24     3     1

In [149]:
df2[df2.var1>15]

var1  var2  var3
1    17     5    10
2    20    26    11
3    23    22     4
9    24     3     1

In [150]:
df2[(df2.var1>15)& (df2.var2>15)]

var1  var2  var3
2    20    26    11
3    23    22     4

In [90]:
df2[df2.var1>15]["var1"]

0    21
1    19
4    25
5    16
6    25
9    16
Name: var1, dtype: int32

In [194]:
df3=pd.DataFrame({'gruplar':['A','B','C','A','B','C'],'veri':[10,11,52,23,43,55]},columns=['gruplar','veri'])
                  

In [155]:
df3

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [195]:
df3.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [160]:
import seaborn as sns
df_p=sns.load_dataset("planets")
df_p

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [161]:
df_p.groupby("method")

In [164]:
df_p.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [165]:
df_p.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

In [166]:
df_p.head(2)

method  number  orbital_period  mass  distance  year
0  Radial Velocity       1         269.300  7.10     77.40  2006
1  Radial Velocity       1         874.774  2.21     56.95  2008

In [ ]:
df.g

In [74]:
?np.random.randint