In [1]:
liste=[1,2,3]

In [2]:
liste

[1, 2, 3]

# Numpy Kütüphanesi

In [2]:
import numpy as np

In [11]:
karma=[1,2,"merve"]
karma


[1, 2, 'merve']

In [12]:
type(karma)

list

In [13]:
a=np.array([1,2,3,4])

In [15]:
type(a)

numpy.ndarray

In [19]:
f=np.array([3.14,5.2,6.8],dtype="int")

In [20]:
f


array([3, 5, 6])

In [18]:
type(f)

numpy.ndarray

In [15]:
c=np.array([1,2,3.14],dtype="int")
c

array([1, 2, 3])

In [21]:
np.array?

In [10]:
#sıfırlardan olusan bir array tanımlama
z=np.zeros(15,dtype="int")
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
z[2]=12

In [12]:
z

array([0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
z2=np.zeros((3,5),dtype="int")

In [21]:
z2


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
birler=np.ones((3,5))

In [23]:
birler

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
?np.ones # yardım dosyasını açar 

In [15]:
fl=np.full((3,5),7.4)
fl

array([[7.4, 7.4, 7.4, 7.4, 7.4],
       [7.4, 7.4, 7.4, 7.4, 7.4],
       [7.4, 7.4, 7.4, 7.4, 7.4]])

In [16]:
sonsuz=np.full((3,5),np.inf)
sonsuz

array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [29]:
ar=np.arange(10)

In [30]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
?np.arange

In [32]:
ters=np.arange(44,23,-3)
ters

array([44, 41, 38, 35, 32, 29, 26])

In [33]:
ln=np.linspace(4,8,10)

In [34]:
ln

array([4.        , 4.44444444, 4.88888889, 5.33333333, 5.77777778,
       6.22222222, 6.66666667, 7.11111111, 7.55555556, 8.        ])

In [19]:
# normal dağılıma uygun rastgele içerikli dizi/matris tanımlama

nd=np.random.normal(5,2,[2,4])
nd

array([[7.82107152, 2.35279956, 2.6170384 , 6.06519116],
       [2.70127643, 6.96714   , 7.34757809, 5.27288605]])

In [23]:
?np.random.normal

In [37]:
#ortalaması 8 standart sapması 3 olan [3,3] bir matris olusturun
np.random.normal(8,3,[3,3])

array([[ 9.15149383,  7.14476377,  5.94878963],
       [ 4.94078655,  3.12504073,  5.44006962],
       [ 6.6122946 ,  7.99641251, 10.61238657]])

In [38]:
np.random.normal(8,3,[3,3])


array([[ 5.89640841,  8.97208239,  9.06990344],
       [ 6.67963963,  5.44426201,  9.57236855],
       [13.04020785,  9.8057206 ,  6.76832099]])

In [21]:
np.random.randint(6,size=10)


array([2, 5, 4, 4, 5, 4, 2, 0, 5, 2])

In [22]:
np.random.randint(3,6,size=10)

array([4, 5, 4, 5, 3, 5, 4, 5, 3, 5])

In [23]:
np.random.randint(0,15,5)


array([ 4,  8, 11, 10,  5])

In [24]:
a=np.random.randint(3,15,[5,3,4])


In [25]:
a


array([[[ 5, 10, 13,  9],
        [ 4,  8,  4,  3],
        [ 8, 13, 10, 11]],

       [[ 6, 12,  5, 13],
        [ 6,  4,  5, 11],
        [11, 14,  3,  6]],

       [[10, 14, 10, 10],
        [12, 13, 14,  6],
        [12, 14,  6, 11]],

       [[12, 10, 11,  4],
        [ 8,  8,  5,  9],
        [10, 11, 12,  9]],

       [[ 4, 11,  8,  4],
        [ 5,  6, 12,  7],
        [ 4,  6,  6, 10]]])

In [26]:
a.ndim

3

In [27]:
a.size

60

In [28]:
a.shape

(5, 3, 4)

In [29]:
a.dtype

dtype('int32')

In [ ]:
a.ndim # boyut sayısı
a.shape # boyut bilgisi
a.size # toplam eleman sayısı

In [42]:
c=np.arange(1,9)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
c.ndim

1

In [35]:
c.shape

(5,)

In [37]:
t=c.reshape(1,5)
t

array([[1, 3, 5, 7, 9]])

In [38]:
t.ndim

2

In [39]:
t.shape

(1, 5)

In [43]:
c.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
t.shape

(9, 1)

In [64]:
zr=np.zeros(10)

In [65]:
zr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
zr.shape

(10,)

In [67]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x=c.reshape(1,9) # matrisin transpozesini alabildim
x

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
x.shape

(1, 9)

In [72]:
c.shape

(9,)

In [44]:
cn=np.array([[1,2],
            [3,4]])

In [45]:
cn

array([[1, 2],
       [3, 4]])

In [49]:
bir=np.concatenate([cn,cn],axis=1) # axis=0 olursa satıra ekliyor(default degeri)
bir

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [50]:
bir.ndim

2

In [51]:
bir.shape

(2, 4)

In [52]:
x=np.array([1,2,3,99,99,3,2,1])
a,b,c=np.split(x,[3,5])

In [53]:
a


array([1, 2, 3])

In [54]:
b

array([99, 99])

In [55]:
c

array([3, 2, 1])

In [59]:
v2=np.random.normal(5,20,[3,3])

In [60]:
v2

array([[  4.42401943,  11.11332053,   5.81898836],
       [ 14.86774474,  23.89006063,   7.62865185],
       [-20.84038754,  -4.23745729,   9.69440027]])

In [63]:
np.sort(v2,axis=0)

array([[-20.84038754,  -4.23745729,   5.81898836],
       [  4.42401943,  11.11332053,   7.62865185],
       [ 14.86774474,  23.89006063,   9.69440027]])

In [85]:
np.sort(v2,axis=1)

array([[-10.97205936,  -2.36313409,  33.16118003],
       [-14.89992019, -11.59784717,  13.47440559],
       [  2.48978073,   9.79683267,  18.61349436]])

In [64]:
#fancy indexleme
v=np.arange(0,30,3)

In [65]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [88]:
v[3]

9

In [89]:
v[8]

24

In [91]:
v[7]


21

In [67]:
lst=[3,8,7]
v[lst]

array([ 9, 24, 21])

In [68]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [69]:
v2=np.reshape(3,3)

ValueError: cannot reshape array of size 1 into shape (3,)

In [42]:
v2=np.arange(0,9).reshape(3,3)

In [43]:
v2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
satir=[0,1,0]
sutun=[2,1,0]
v2[satir,sutun]


array([2, 4, 0])

In [70]:
a=np.array([0,1,2,3,4])

In [71]:
a


array([0, 1, 2, 3, 4])

In [72]:
bind=a>2

In [73]:
bind

array([False, False, False,  True,  True])

In [74]:
a[bind]

array([3, 4])

In [46]:
a[a>2] # boolean index

array([3, 4])